In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
datascore = pd.read_csv('score.csv')

In [3]:
datascore.head()

Teams  points   runs  won
0   Hyd    34.0  198.0  yes
1   Che    28.0    NaN   no
2  Punj     NaN    NaN   no
3   Hyd     NaN  182.0  yes
4   Del    30.0  172.0   no

In [4]:
X = datascore.iloc[:, :-1].values
y = datascore.iloc[:, 3].values

In [5]:
X

array([['Hyd', 34.0, 198.0],
       ['Che', 28.0, nan],
       ['Punj', nan, nan],
       ['Hyd', nan, 182.0],
       ['Del', 30.0, 172.0],
       ['Che', nan, 177.0],
       ['Punj', 27.0, nan],
       ['Del', 32.0, 188.0]], dtype=object)

In [6]:
# using Imputer for replace the empty cell with value in dataset
from sklearn.preprocessing import Imputer

In [7]:
dataimp = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
dataimp = dataimp.fit(X[:, 1:3])
dataimp
X[:, 1:3] = dataimp.transform(X[:, 1:3])

c:\python\lib\site-packages\sklearn\utils\deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [8]:
X

array([['Hyd', 34.0, 198.0],
       ['Che', 28.0, 183.4],
       ['Punj', 30.2, 183.4],
       ['Hyd', 30.2, 182.0],
       ['Del', 30.0, 172.0],
       ['Che', 30.2, 177.0],
       ['Punj', 27.0, 183.4],
       ['Del', 32.0, 188.0]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
labelencode_y = LabelEncoder()
y = labelencode_y.fit_transform(y)
y

array([1, 0, 0, 1, 0, 0, 1, 1])

In [11]:
labelencoder_x = LabelEncoder()
X[:, 0] = labelencoder_x.fit_transform(X[:, 0])
X

array([[2, 34.0, 198.0],
       [0, 28.0, 183.4],
       [3, 30.2, 183.4],
       [2, 30.2, 182.0],
       [1, 30.0, 172.0],
       [0, 30.2, 177.0],
       [3, 27.0, 183.4],
       [1, 32.0, 188.0]], dtype=object)

In [12]:
from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder(categorical_features= [0])
X = onehotencoder.fit_transform(X).toarray()
X

c:\python\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
c:\python\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[  0. ,   0. ,   1. ,   0. ,  34. , 198. ],
       [  1. ,   0. ,   0. ,   0. ,  28. , 183.4],
       [  0. ,   0. ,   0. ,   1. ,  30.2, 183.4],
       [  0. ,   0. ,   1. ,   0. ,  30.2, 182. ],
       [  0. ,   1. ,   0. ,   0. ,  30. , 172. ],
       [  1. ,   0. ,   0. ,   0. ,  30.2, 177. ],
       [  0. ,   0. ,   0. ,   1. ,  27. , 183.4],
       [  0. ,   1. ,   0. ,   0. ,  32. , 188. ]])

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [17]:
X_train

array([[ 1.41421356, -0.70710678, -0.70710678,  0.        , -1.46615701,
         0.        ],
       [-0.70710678,  1.41421356, -0.70710678,  0.        ,  0.67943861,
         0.55837964],
       [-0.70710678, -0.70710678,  1.41421356,  0.        , -0.28607942,
        -0.16994163],
       [-0.70710678, -0.70710678,  1.41421356,  0.        ,  1.75223642,
         1.77224841],
       [ 1.41421356, -0.70710678, -0.70710678,  0.        , -0.28607942,
        -0.77687602],
       [-0.70710678,  1.41421356, -0.70710678,  0.        , -0.3933592 ,
        -1.38381041]])

In [18]:
X_test

array([[-0.70710678, -0.70710678, -0.70710678,  1.        , -2.00255591,
         0.        ],
       [-0.70710678, -0.70710678, -0.70710678,  1.        , -0.28607942,
         0.        ]])